version: "3"

services:
    todoql:
        container_name: todoql
        image: todoql
        ports:
          - 8080:8080
        depends_on:
            - todoql_mysql
    todoql_mysql:
        container_name: todoql_mysql
        hostname: todoql_mysql
        image: todoql_mysql:latest
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: todoql
            MYSQL_ROOT_PASSWORD: pass
